services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    container_name: hackathon-database
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
